### PR TITLE
Update nix package

### PR DESCRIPTION
**Pull request by LostAttractor**
Updated yarn.nix to update dependencies
And I also rearranged and update package version number in release.nix

### CODE REVIEW

**Comment by LostAttractor** [comment]
Also, I wrote a pull request to add kuro to the official nix package repository (nixpkgs)
`https://github.com/NixOS/nixpkgs/pull/211022`

**Comment by LostAttractor** [comment]
Previously, because of some misunderstandings about the use input-methods on electron apps  on nixos, multiple force pushes were performed
Now this pull request is ready for review!

**Comment by davidsmorais** [comment]
@LostAttractor , thanks for this 👍  Is there a comand I can run in order to update the `nix` package whenever I release a new version Kuro or must I do this manually ?

**Review by davidsmorais — APPROVED** [review]

**Comment by LostAttractor** [comment]
For electron, we may have multiple electron applications, but their electron binary is the same, so we can directly use the electron package of the system.
And for the node package, because yarn is used, we can use `yarn2nix`
https://nixos.wiki/wiki/Node.js
`yarn2nix > yarn .nix`

**Pull request merged**
